apiVersion: v2
name: app-HelmChart
description: <description>
type: application
version: 0.1.0 #Helm Chart version
appVersion: "1.0.0" #Application version

keywords:
  - apache
  - http
  - https
  - ilia-vorobyou

maintainers:
  - name: Ilia Vorobyou
    email: vorbev.ilya@mail.ru
    url: www.ilia.com
