apiVersion: v1
kind: Service
metadata:
  labels:
    app: apache-service
  name: apache-service
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: {{ .Release.Name }}-apache