apiVersion: v1
kind: Service
metadata:
  name: apache-service
spec:
  type: NodePort
  selector:
    project: {{ .Release.Name }}-apache
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
