apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nginx-service
spec:
  type: NodePort
  selector:
    project: {{ .Release.Name }}-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001  